# pyproject.toml
[build-system]
requires = [
    "pip>=22.1",
    "setuptools>=60.0.0",
    "setuptools_scm[toml]>=6.4.2",
    "wheel>=0.37",
    "pip-tools>=6.6.2",
    "build>=0.8.0"
]

build-backend = "setuptools.build_meta"
